Repository openstack-k8s-operators/keystone-operator, pull requests merged in 2022-10, with the labels that each got.

#105 Set image defaults to tripleowallabycentos9
  README.md
  config/samples/keystone_v1beta1_keystoneapi.yaml
Labels: approved

#113 Only add finalizer and update instance if necessary
  controllers/keystoneapi_controller.go
  controllers/keystoneendpoint_controller.go
  controllers/keystoneservice_controller.go
Labels: approved, lgtm

#108 Clarify which containers are used
  README.md
Labels: approved, needs-ok-to-test, lgtm
