Repository openstack-k8s-operators/keystone-operator, pull requests merged in 2024-02, with the labels that each got.

#361 Drop Debug fields
  api/bases/keystone.openstack.org_keystoneapis.yaml
  api/v1beta1/keystoneapi_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/keystone.openstack.org_keystoneapis.yaml
  config/samples/keystone_v1beta1_keystoneapi.yaml
  pkg/keystone/bootstrap.go
  pkg/keystone/cronjob.go
  pkg/keystone/dbsync.go
  pkg/keystone/deployment.go
  tests/kuttl/common/assert_sample_deployment.yaml
  tests/kuttl/tests/keystone_scale/03-assert.yaml
Labels: approved, lgtm

#364 FIPS compliant images
  .prow_ci.env
  Dockerfile
  Makefile
Labels: approved, lgtm

#366 bump mariadb dependency and fix envtest
  config/rbac/role.yaml
  controllers/keystoneapi_controller.go
  go.mod
  go.sum
  tests/functional/keystoneapi_controller_test.go
  tests/kuttl/common/assert_sample_deployment.yaml
  tests/kuttl/tests/keystone_scale/03-assert.yaml
  tests/kuttl/tests/keystone_tls/01-assert.yaml
Labels: approved, lgtm

#368 Render service config in operator and store in secret
  controllers/keystoneapi_controller.go
  pkg/keystone/bootstrap.go
  pkg/keystone/cronjob.go
  pkg/keystone/dbsync.go
  pkg/keystone/deployment.go
  pkg/keystone/initcontainer.go
  pkg/keystone/volumes.go
  templates/common/common.sh
  templates/keystoneapi/bin/init.sh
  templates/keystoneapi/config/keystone-api-config.json
  templates/keystoneapi/config/keystone.conf
  tests/functional/keystoneapi_controller_test.go
  tests/kuttl/common/assert_sample_deployment.yaml
  tests/kuttl/tests/keystone_tls/01-assert.yaml
Labels: approved, lgtm

#369 Add fips compliant annotation
  config/manifests/bases/keystone-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#370 Fix reconcileDelete during namespace delete
  controllers/keystoneendpoint_controller.go
  controllers/keystoneservice_controller.go
Labels: approved, lgtm

#363 Controller runtime Update
  .ci-operator.yaml
  .github/workflows/build-keystone-operator.yaml
  Dockerfile
  api/bases/keystone.openstack.org_keystoneapis.yaml
  api/go.mod
  api/go.sum
  api/v1beta1/keystoneapi_webhook.go
  config/crd/bases/keystone.openstack.org_keystoneapis.yaml
  controllers/keystoneapi_controller.go
  go.mod
  go.sum
  main.go
  tests/functional/suite_test.go
Labels: do-not-merge/hold

#372 Unique LeaderElectionID
  main.go
Labels: lgtm

#375 Sync EnvTest version with k8s version
  Makefile
Labels: approved, lgtm

#376 [renovate]Remove golang constraint
  renovate.json
Labels: approved, lgtm

#382 Regenerate go.mod indirect dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm

#346 Enable Secure RBAC by default
  api/bases/keystone.openstack.org_keystoneapis.yaml
  api/v1beta1/keystoneapi_types.go
  config/crd/bases/keystone.openstack.org_keystoneapis.yaml
  controllers/keystoneapi_controller.go
  templates/keystoneapi/config/keystone.conf
Labels: approved, lgtm

#374 Bump golangci-lint
  .golangci.yaml
  .pre-commit-config.yaml
Labels: approved, lgtm

#383 [tlse] TLS database connection
  controllers/keystoneapi_controller.go
  templates/keystoneapi/config/keystone-api-config.json
  tests/functional/keystoneapi_controller_test.go
Labels: approved, lgtm
